name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "20 22 * * 0"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
        environment-file: ["environment.yaml"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: "latest"
          extra-specs: python=${{ matrix.python-version }}
          channel-priority: "flexible"

      - name: install stac-static
        run: pip install .

      - name: run tests
        id: status
        run: pytest -v --cov --cov-report term-missing .

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install with test dependencies
        run: pip install .[dev]

      - name: Execute linters & type checkers
        run: pre-commit run --all-files